### PR TITLE
yaml based configuration instead of loose txt files

### PR DESCRIPTION
**Pull request by dgomes**
Trying to bring all configurations into a yaml file (HomeAssistant.io biased developer here)

### CODE REVIEW

**Comment by oskarn97** [comment]
thanks a lot for this!
Yeah, I was thinking about doing the same but was too lazy :P
Have you tested it?

**Comment by dgomes** [comment]
running on my setup :)

Also did some other improvements on mqtt protocol usage (last will, and retain devices topic)

**Comment by dgomes** [comment]
Forgot to mention, changed the /dev path to support OSX also

**Comment by oskarn97** [comment]
Cool!
Thanks a lot!

Could you change the defaults to (for backwards compatibility)
```
server: localhost
base_topic: xiaomi
port: /dev/ttyACM0
```

I'll merge it then ;-)

**Comment by oskarn97** [comment]
The reason is that this module is used in some tutorials regarding FHEM and Xiaomi

**Comment by dgomes** [comment]
Have you been successful at contacting the upstream author ?

**Comment by oskarn97** [comment]
Thanks!
Unfortunately not, I've tried it on GitHub, Twitter and LinkedIn but no reaction so far.
I've posted an issue with the link to this fork for anyone else looking.
Will merge now!

**Comment by oskarn97** [comment]
I'll be cool if you could add the bridgeID to the config file as well using "bridge" as default value.
Then it's unified.

**Comment by dgomes** [comment]
This guy is also hot _right_ now :) 

https://github.com/Koenkk/xiaomi-zb2mqtt

We should bring him into the loop too

**Comment by oskarn97** [comment]
yeah definitely!
This repo is some improvements ahead regarding filtering, new devices, battery messages etc he could definitely use.
Also, the firmware with a maximum of 48 instead of 20 devices is kinda important (at least for me).

**Comment by dgomes** [comment]
please go ahead and contact him, I'll update the bridgeId meanwhile ;)

**Comment by oskarn97** [comment]
sure thing, thanks

**Pull request merged**
