### PR TITLE
Battery level as percentage

### PR DESCRIPTION
**Pull request by juliojs**
Just a small change to calculate the battery percentage based on voltage.
This first aproximation is considering 2.5V (2500) as minimum and 3.0V (3000) as maximum for the CR2032 battery, it's necessary to confirm that this is correct for xiaomi devices...

### CODE REVIEW

**Comment by oskarn97** [comment]
Hey,
thank you for your contribution!
As for consistency with software that already uses this implementation please do not change the data format of existing readings like battery_level. Please feel free to add an additional reading instead.

**Comment by juliojs** [comment]
Ooops! I didn't notice that sorry, I was just testing on my installation. I've just added a configuration option to send the battery_level as percentage or as voltage, it's not pretty but it'll work! ;)

How about merging this with @Koenkk's and @starkun 's versions, all of you are doing an impressive work, It would be great to see a merged version!

**Comment by dgomes** [comment]
Don't know whats wrong with this community... everyone just forks and reinvents the wheel 😞

**Comment by starkun** [comment]
13:25, 20 апреля 2018 г., Diogo Gomes <notifications@github.com>:Don't know whats wrong with this community... everyone just forks and reinvents the wheel <g-emoji class="g-emoji" alias="disappointed" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f61e.png">😞

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




I only make a port work of kirovilya. And it forks fine. Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by oskarn97** [comment]
Merged - thanks for your contribution!

**Pull request merged**
